trigger: none
pr: none

pool:
  vmImage: windows-latest

variables:
- group: variable-group-name
- name: variable-name
  value: variable-value

steps:
  - template: template/deploy-steps.yml
    parameters:
      blobName: $(CertificatePPEBlobName)
      certificateFileName: $(CertificateFileName)
